language: cpp
dist: trusty
sudo: require
os:
- linux
- osx
compiler:
- clang
- gcc
matrix:
  exclude:
  - os: linux
    compiler: clang
  - os: osx
    compiler: gcc
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - cmake
    - libx11-dev
    - libudev1
    - libudev-dev
    - gcc-4.9
    - g++-4.9
    - libbz2-dev
    - libstdc++-4.9-dev
    - sshpass
before_install:
- cmake --version
- $CC --version
- $CXX --version
- if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then sudo apt-get update -q ; fi
- if [[ "$TRAVIS_OS_NAME" = "linux" ]] ; then  sudo apt-get install libudev1 -y ; fi
- if [ "$CXX" = "g++" ] && [ "$TRAVIS_OS_NAME" = "linux" ] ; then export CXX="g++-4.9"
  CC="gcc-4.9"; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install http://git.io/sshpass.rb ; fi
script:
- mkdir build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- make
- export SSHPASS=$DEPLOY_PASS
- sshpass -e ssh -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST mkdir -p /home/$DEPLOY_USER/XsaitekpanelsFromTravis/${TRAVIS_COMMIT}
- sshpass -e ssh -oStrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST mkdir -p /home/$DEPLOY_USER/XsaitekpanelsFromTravis/latest
# - sshpass -e scp ../bin/Xsaitekpanels/*.xpl  $DEPLOY_USER@$DEPLOY_HOST:/home/$DEPLOY_USER/XsaitekpanelsFromTravis/${TRAVIS_COMMIT}
- sshpass -e ssh $DEPLOY_USER@$DEPLOY_HOST cp /home/$DEPLOY_USER/XsaitekpanelsFromTravis/${TRAVIS_COMMIT}/*.xpl /home/$DEPLOY_USER/XsaitekpanelsFromTravis/latest/
after_success:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then otool -L ../bin/Xsaitekpanels/*.xpl ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; ldd ../bin/Xsaitekpanels/*.xpl ; fi
env:
   global:
   - secure: SDnLn9ETjoLTmTcg9NTNqyMRU8Tj/1bQG7eGJxdZIes11uYsEqQlLijreTVPEmKhOSxP5Yy5/x96R8LCpPS8WkJgOCUeoBELbt0wyDn3mxwrFhw80U9aUiZVQH8SRr9mhTMeTPNBJ2sxQe/Vw77idG59t2hgAkwgqxOBZtVzhta3lw1UYYCtYv7p5huzg+RB77MVs3Tn4iyOHsJBCyzxzvqtD3va0V4fASZSCmRk++toTEBorPT2pnawUAZVMqK84KRfVVAlBKpObmxGCR7dUQBZJGleST9pLyQSNgC9QzeV0h0GIH3no8q18h0yxwfX7G9DLq3/62Vzg4g9+xLxeB9qagfT6GZeE0iWM+eJHzDVvfzZW8Vyxtd7ugD4U+v+LHT3aCfwuDj05a3fq0D4EIOpf1iPchg5V+Msll9iB6ajwiDWtf1ZC77TQ/PH8fXjHv52jBryhNmtdjLN2I09fhcEr2Y7/j+4Fkz+QhFylUr9BZaGnnvca/uz0HNhw54yg6ZH8JsRZrTddiLyCVX5L1K4UJAkDu9raLk1Mg0D3/z0Dmv2H1RuzLMx1BLKI+nJ9ylKgX7iLmf3kR7FRUc0HCUg4mDG7ktLnlP96iJ5WPPY3AnQ8wA0tMZeB3kk1i++kNJTwcutGvdMP/MBRFCzOVU9lp7J6JM7Atv7w7EsoPI=
   - secure: I4eugENXadVWEglQqaZBMyP326LF5ahZmYOHh6HAUFeeloj+wm7YqFTQiRsl/BoMWY+UqtHFiuuwo1sLw1fr1D3E06dZGW0NH0ogqNiHAt4Nm6+A5QKEZReWzBhdQ0rlug3ek3jhrQA0+A0XskhdJ6/VfCsE0Yu4Hi79zsUJ8rlmb+FLKTcsAHFzQpe7XXrGmfcT8ftPVC5S3x4EoV7bNZYxH/zJJ1g2rEtDncRBrvuURJt+JmHp15w+Ykgiqke+ypqVrvdCxKnHu8Tz+3xVh3YhQnvBzluQAjmyZ2fxQh2mmb4Y5j2rLwFIizqjxBisiv62EUOR5MswQa7SRyx8HLvlZW2NE4dw98xJD/9KqaE+zX8/Ti4K+wBxzg+T/BPpbSiq2GUs9p0xpuiGCz+wYyS7Qzytp0LTORwaClz8nunKeLjGXQskQk1JBG6Fd0fl5x7Jx/bwer8MwYWLjCNRINEv6biRegC1yDVdGrEASST4hoX3Q0Z6OjQEfuFPA127fprF0hU0GK0l5q7aGEwGOm3GejW5We8kpp5vvNhdWSRH/9U+cVuC4+Qw+N3JB3DgZEU3xZMB8keQ3IhB0PVcHX7WW/jePUv6Ed2X5szEkFjo9wj/qMazW2eWOtV0rWwZ+/34CFT95EnP7fJZtJTVamZdcadWzD1ygzwTCYC/Qmw=
   - secure: h/KX409IyyyMv0g3t8eIsnw3FtCj0biq4dybHhtJ6vptJpdIWhZqBs7LEtIjGXvKJNKUq7fKDaCcMkJhP8JTf/4B1Q5HEQ00GkKSVM2EsmrmntAPm+Sy57TWziNQkxa/5QmeLoTgJuVui+6dCrQAq/bej+9k3fJ1HuRudQl0nBVAgyoTK3ENIe94+ADC5zuRyyhPIRRyDL6ETnyPOcLImd0c4G+c0wEpKNGFKAQTuFRD/I+BQxyq7ynwPeqJdOB3FbrhvAUOzZX93dMCB9Z3CM2u7+Wr3XTAxAq10IAjpR4wTlGUyebcc09F7a/IYPhn2PTZUHVavM06RiCMyaELLaHqZfm/vbupoPuMAulDCvq1RyyBRsJVlj8ykf7fmxJx9VxTtXPkMrGttBuduD6SM1nIzlgpGdmnC0eYuHqUuX/Cv3Etn5KkZAmaDyjxwgNSfhftq6tFEnfvQAIP/t+14D1BC5M9sUJj7a7sjPmpfXA5E7vHAWdiFnWTUOTRyEIaW95Eq4+tzCMzaNzU5zYASlwzfRBlBCXKlXP0crR7MUqraSZaIC9AqTAPfyH21Tx+uCEJYziXQmUHQSG2fT1ST+b1vOTw5qgFdE5GDcmEvwRGhRFsU5yn0Auc0puQFPxHAfEx5mHZErwYxJfpx2JbfLIQmTd4F565P9LwAAUWLVQ=
